apiVersion: v1
kind: Service
metadata:
  labels:
    app: seenivasan-test
  name: seenivasan-test
  namespace: seenivasan-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: seenivasan-test
  type: NodePort
status:
  loadBalancer: {}
