apiVersion: v1
kind: Service
metadata:
  labels:
    app: testgit-poc
  name: testgit-poc
  namespace: codefresh-poc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: testgit-poc
  type: NodePort
status:
  loadBalancer: {}
